spring:
  datasource:
    url: jdbc:mysql://localhost/toolkit-inventory
    username: genesis
    password: svgfile#828

  data:
    rest:
      detection-strategy: ANNOTATED
      base-path: api

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

allowed:
  origins: http://localhost


server:
  port: 8443
